name: Extract GameInformation

on:
  schedule:
    - cron: '50,30 8 * * *' #大约每日16点40,17点00,两个时间点执行任务(gh服务器延迟问题)
  watch:
      types: [started]
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  PYTHONIOENCODING: utf-8

# Allow Release
permissions: write-all

jobs:
  build:
    name: 'Extract GameInformation Operations'
    runs-on: "windows-latest"

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Checkout private repo
        uses: actions/checkout@v2

      - name: Setup Extractor  
        run: |
          git clone -b main https://${{ secrets.GIT_AUTH_TOKEN }}:x-oauth-basic@github.com//yuhao7370/Phigros_Extractor.git
          pip3 install -r Phigros_Extractor/requirements.txt
        shell: bash  

      - name: Execute Extractor
        id: operation
        run:  python3 Phigros_Extractor/GithubActions.py 
      
      - name: Cleanind
        id: clean
        run:  python3 clean.py 

      - name: commit
        env:
          useremail: ${{ secrets.GH_EMAIL }}
        run: |
          git config --global user.email useremail
          git config --global user.name GithubActionBot
          if [ -n "$(git status -s)" ];then
              git add .
              git commit -m "仓库更新" -a
          fi
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_AUTH_TOKEN }}
  
      # - name: Pushing illu
      #   uses: ncipollo/release-action@v1
      #   with:
      #     name: "Phigros Illustration"
      #     body: >-
      #       Phigros Illustration
      #     commit: ${{ github.sha }}
      #     tag: "illu"
      #     # artifacts: Phigros_Extractor\prehandle\*
      #     artifacts: Phigros_Extractor\Illustrations.zip

      #     allowUpdates: true
      #     removeArtifacts: true
      #     replacesArtifacts: true

      # - name: Pushing CT
      #   uses: ncipollo/release-action@v1
      #   with:
      #     name: "Phigros Constant Table"
      #     body: >-
      #       Phigros Constant Table
      #     commit: ${{ github.sha }}
      #     tag: "table"
      #     artifacts: Phigros_Extractor\Assets\ConstantTable\Generated\*

      #     allowUpdates: true
      #     removeArtifacts: true
      #     replacesArtifacts: true

      # - name: Pushing to release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     name: "Phigros Gameinformation"
      #     body: >-
      #       Phigros Gameinformation
      #     commit: ${{ github.sha }}
      #     tag: "info"
      #     artifacts: Phigros_Extractor\Assets\GameInformation\*

      #     allowUpdates: true
      #     removeArtifacts: true
      #     replacesArtifacts: true

