name: Extract GameInformation

on:
  schedule:
    - cron: '50,30 16 * * *' #大约每日16点40,17点00,两个时间点执行任务(gh服务器延迟问题)
  watch:
      types: [started]
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  PYTHONIOENCODING: utf-8

# Allow Release
permissions: write-all

jobs:
  build:
    name: 'Extract GameInformation Operations'
    runs-on: "windows-latest"

    steps:
      - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
        with:
          timezoneWindows: "Asia/Shanghai"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Checkout private repo
        uses: actions/checkout@v2

      - name: Setup Extractor  
        run: |
          git clone -b main https://${{ secrets.GIT_AUTH_TOKEN }}:x-oauth-basic@github.com//yuhao7370/Phigros_Extractor.git
          pip3 install -r Phigros_Extractor/requirements.txt
        shell: bash  

      - name: Execute Extractor
        id: operation
        run:  python3 Phigros_Extractor/GithubActions.py 

      - name: Pushing to release
        uses: ncipollo/release-action@v1
        with:
          name: "Phigros Gameinformation"
          body: >-
            Phigros Gameinformation
          commit: ${{ github.sha }}
          tag: "info"
          artifacts: Phigros_Extractor\Assets\GameInformation\*

          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
